#!/bin/bash

### SkyWire Start script, manager & node

# ENV vars
Manager_Pid_FILE=manager.pid
Node_Pid_FILE=node.pid
GOEXEC_DIR=/usr/local/go
GOBIN_DIR=/usr/local/skywire/go
TMP_DIR=/tmp/skywire-pids
Need_Kill=no
Web_Dir=/usr/local/skywire/go/src/github.com/skycoin/skywire/static/skywire-manager

# export/expose some of the vars to go
export HOME=/root
export GOPATH=${GOBIN_DIR}

# check for temp dir to hold the pids
if [[ ! -d ${TMP_DIR} ]]; then
	mkdir -p ${TMP_DIR}
fi

# Catch one optional argument: "yes" (to kill previous instances before start)
[[ ! -z $1 ]] && Need_Kill=$1

# kill previous instances before start is intructed to.
if [ $Need_Kill = "yes" ];then
	# manager
	[[ -f ${TMP_DIR}/${Manager_Pid_FILE} ]] && pkill -F "${TMP_DIR}/${Manager_Pid_FILE}" && rm "${TMP_DIR}/${Manager_Pid_FILE}"
	# node
	[[ -f ${TMP_DIR}/${Node_Pid_FILE} ]] && pkill -F "${TMP_DIR}/${Node_Pid_FILE}" && rm "${TMP_DIR}/${Node_Pid_FILE}"
fi

# check if we have the bins in place, otherwise compile it from source and if old bins are found remove them
command -v "${GOBIN_DIR}/bin/manager" && command -v "${GOBIN_DIR}/bin/node" && command -v "${GOBIN_DIR}/bin/socksc" && command -v "${GOBIN_DIR}/bin/sockss" && command -v "${GOBIN_DIR}/bin/sshc" && command -v "${GOBIN_DIR}/bin/sshs" > /dev/null || {
		[[ -d ${GOBIN_DIR}/pkg/linux_arm64/github.com/skycoin ]] && rm -rf ${GOBIN_DIR}/pkg/linux_arm64/github.com/skycoin
		cd ${GOBIN_DIR}/src/github.com/skycoin/skywire/cmd
		${GOEXEC_DIR}/bin/go install ./... 2>> /tmp/skywire_install_errors.log
}

# start routine manager & node
echo "Starting SkyWire Manager"
cd ${GOBIN_DIR}/bin/
nohup ./manager -web-dir ${Web_Dir} > /dev/null 2>&1 &
echo $! > "${TMP_DIR}/${Manager_Pid_FILE}"
cat "${TMP_DIR}/${Manager_Pid_FILE}"
nohup ./node -connect-manager -manager-address 192.168.0.2:5998 -manager-web 192.168.0.2:8000 -discovery-address discovery.skycoin.net:5999-034b1cd4ebad163e457fb805b3ba43779958bba49f2c5e1e8b062482904bacdb68 -address :5000 -web-port :6001  > /dev/null 2>&1  &
echo $! > "${TMP_DIR}/${Node_Pid_FILE}"
cat "${TMP_DIR}/${Node_Pid_FILE}"
cd /root
echo "SkyWire Manager Done"
