#!/bin/bash

### SkyWire Start script, manager & node

# check for the env vars
if [ ! -f /etc/default/skywire ] ; then
	# does not exist, link it
	ln -s /usr/local/skywire/go/src/github.com/skycoin/skywire/static/script/skywire.defaults /etc/default/skywire
fi 

# now load it
. /etc/default/skywire

# check for temp dir to hold the pids
if [[ ! -d ${TMP_DIR} ]] ; then
	mkdir -p ${TMP_DIR}
fi

# Catch one optional argument: "yes" (to kill previous instances before start)
[[ ! -z $1 ]] && Need_Kill=$1

# kill previous instances before start is intructed to.
if [ "$Need_Kill" == "yes" ] ; then
	# manager
	[[ -f ${Manager_Pid_FILE} ]] && pkill -F "${Manager_Pid_FILE}" && rm "${Manager_Pid_FILE}"
	# node
	[[ -f ${Node_Pid_FILE} ]] && pkill -F "${Node_Pid_FILE}" && rm "${Node_Pid_FILE}"
fi

# check if we have the bins in place, otherwise compile it from source and if old bins are found remove them
command -v "${GOPATH}/bin/manager" && command -v "${GOPATH}/bin/node" && command -v "${GOPATH}/bin/socksc" && command -v "${GOPATH}/bin/sockss" && command -v "${GOPATH}/bin/sshc" && command -v "${GOPATH}/bin/sshs" > /dev/null || {
		[[ -d ${GOPATH}/pkg/linux_arm64/github.com/skycoin ]] && rm -rf ${GOPATH}/pkg/linux_arm64/github.com/skycoin
		cd ${GOPATH}/src/github.com/skycoin/skywire/cmd
		${GOROOT}/bin/go install ./... 2>> /tmp/skywire_install_errors.log
}

# start routine manager & node
echo "Starting SkyWire Manager"
cd ${GOPATH}/bin/
nohup ./manager -web-dir ${Web_Dir} > /dev/null 2>&1 &
echo $! > "${Manager_Pid_FILE}"
cat "${Manager_Pid_FILE}"
nohup ./node -connect-manager -manager-address 192.168.0.2:5998 -manager-web 192.168.0.2:8000 -discovery-address ${DISCOVERY_ADDR} -address :5000 -web-port :6001  > /dev/null 2>&1  &
echo $! > "${Node_Pid_FILE}"
cat "${Node_Pid_FILE}"
cd /root
echo "SkyWire Manager Done"
