#!/bin/bash

### SkyWire Start script, only node

# check for the env vars
if [ ! -f /etc/default/skywire ] ; then
	# does not exist, link it
	ln -s /usr/local/skywire/go/src/github.com/skycoin/skywire/static/script/skywire.defaults /etc/default/skywire
fi 

# now load it
. /etc/default/skywire

# check for temp dir to hold the pids
if [[ ! -d ${TMP_DIR} ]] ; then
	mkdir -p ${TMP_DIR}
fi

# Catch one optional argument: "yes" (to kill previous instances before start)
[[ ! -z $1 ]] && Need_Kill=$1

# kill previous instances before start is intructed to.
if [ "$Need_Kill" == "yes" ] ; then
	# only node
	[[ -f ${TMP_DIR}/${Node_Pid_FILE} ]] && pkill -F "${TMP_DIR}/${Node_Pid_FILE}" && rm "${TMP_DIR}/${Node_Pid_FILE}"
fi

# check if we have the bins in place, otherwise compile it from source and if old bins are found remove them
command -v "${GOPATH}/bin/manager" && command -v "${GOPATH}/bin/node" && command -v "${GOPATH}/bin/socksc" && command -v "${GOPATH}/bin/sockss" && command -v "${GOPATH}/bin/sshc" && command -v "${GOPATH}/bin/sshs" > /dev/null || {
	  [[ -d ${GOPATH}/pkg/linux_arm64/github.com/skycoin ]] && rm -rf ${GOPATH}/pkg/linux_arm64/github.com/skycoin
			  cd ${GOPATH}/src/github.com/skycoin/skywire/cmd
			  ${GOROOT}/bin/go install ./... 2>> /tmp/skywire_install_errors.log
}

# start routine only node
cd ${GOPATH}/bin/
nohup ./node -connect-manager -manager-address 192.168.0.2:5998 -manager-web 192.168.0.2:8000 -discovery-address discovery.skycoin.net:5999-034b1cd4ebad163e457fb805b3ba43779958bba49f2c5e1e8b062482904bacdb68 -address :5000 -web-port :6001  > /dev/null 2>&1  &
echo $! > "${Node_Pid_FILE}"
npid=`cat "${Node_Pid_FILE}"`
echo "SkyWire Node started, pid: $npid"
cd /root