#!/bin/bash

MANAGER_PID="manager.pid"
NODE_PID="node.pid"

cd ${GOPATH}/src/github.com/skycoin/skywire
git reset --hard > /dev/null 2>&1
git clean -f -d > /dev/null 2>&1
git pull origin master > /dev/null 2>&1
git pull > /dev/null 2>&1

exec ${GOPATH}/src/github.com/skycoin/skywire/static/script/unix/start

