#!/bin/bash

# local vars
SKYWIRE_UNIX_SCRIPTS=/usr/local/skywire/go/src/github.com/SkycoinProject/skywire/static/script

# check for the env vars
if [ ! -f /etc/default/skywire ] ; then
	# does not exist, link it
	ln -s ${SKYWIRE_UNIX_SCRIPTS}/skywire.defaults /etc/default/skywire
fi 

# now load it
. /etc/default/skywire

# change to work dir
cd ${SKYWIRE_DIR}

# reset to master
git checkout master

# save the only local config we need: the MANAGER_IP
MIP=`cat /etc/default/skywire | grep MANAGER_IP | grep '=' | cut -d '=' -f 2`

# reset any local changes
git reset --hard > /dev/null 2>&1

# clean any untracked file/folder
git clean -f -d > /dev/null 2>&1

# pull changes
git pull origin master > /dev/null 2>&1

# once more, there are reports that it need it
# TODO review this.
git pull > /dev/null 2>&1

# replace the default MANAGER_IP with the custom one, if need
NMIP=`cat /etc/default/skywire | grep MANAGER_IP | grep '=' | cut -d '=' -f 2`
if [ "$MIP" != "$NMIP" ] ; then
	sed -i s/"=$NMIP"/"=$MIP"/ /etc/default/skywire
fi

# TODO needs revision, see:
# https://github.com/SkycoinProject/skywire/issues/161
exec ${SKYWIRE_UNIX_SCRIPTS}/unix/start
